### ISSUE TITLE
Consult the details of DropMessage in the code

### ISSUE THREAD

**Issue by HazeDT** [LuckyTiger123/DropMessage#2]
Appreciate your work.

But when I read the code, I only found DropNode, DropEdge, and Dropout in the layer.DropBlock.  Besides, only this part is related to DropMessage.
![image](https://user-images.githubusercontent.com/38973286/226587557-9e2003e2-2b96-4bc1-906f-5b8da54ed9c6.png)

May I ask which part of the code DropMessage is in? And how it works in the model? 

Grateful.

**Comment by LuckyTiger123** [comment]
Only DropMessage assigns `message_drop` a non-zero value at this step. This parameter will be passed to the backbone model at line 80 of the file `src/layer.py`. You can see the code with the comment `drop messages` in the `message` function of various backbone models in the file `src/backbone.py`. We implement DropMessage by conducting random dropping in the `message` function.
